# Site
repository: Cheukting/Cheukting.github.io
# favicon: images/favicon.ico

# Personal info
name: Cheuk Ting Ho
title: Wishlist for animal corssing items.
email:
phone:
website:
description: >
  I play Animal Crossing New Horison and there are items that I really wanted. Would like to trade with you.
url: https://wishlist.cheuk.dev
baseurl: ""
permalink: /:year/:month/:day/:title/

# Social links
twitter_username: cheukting_ho
github_username:  Cheukting
facebook_username: cheuk
instagram_username: cheuk
pinterest_username: cheuk
youtube_username: cheuk
devto_username: cheukting_ho
twitch_username: cheukting_ho
discord_username: cheukting#4104

# About Section
about_title: About My Island - Pearidise
about_profile_image: images/pear-clipart.png
about_content: | # this will include new lines to allow paragraphs
    Pearidise is an island with Pears grwoing natively and have 5 lovely villagers: Diva, Mac, Jacob, Pango, Midge. On the island we have a townhall, a Nook Cannny and a Able Sister's tailor shop. Most places can be visit via bridges and inclines so venturing pole and ladders are not nessasary. Come and visit us on Pearidise.

# More Section
more_title: Want to trade with me? #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  If you have an item in my wishlist that you have and/ or there is an item in my give away list that you want, please contact me on Discord.

# Footer
footer_show_references: true

plugins:
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-linkpreview

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "package.json",
  "gulpfile.js",
  "scripts/",
  ]
